### ISSUE TITLE
Where can I download the pre-trained dataset for Uniref50?

### ISSUE THREAD

**Issue by changweioy** [maovshao/PLMSearch#2] opened 2024-04-19 08:03 UTC

**Comment by maovshao** [comment] 2024-04-22 05:27
Thank you for your suggestion.

Due to the large amount of data in the ESM-1b embedding of Uniref50, we currently have no plans to release it. However, it may still be released as our subsequent projects progress.

I will keep this issue open, and I will update here if there are any latest developments. Thank you.

**Comment by changweioy** [comment] 2024-05-06 04:16
Thank you for your response. Additionally, could you provide a download link for the Pfam results from UniRef50? I have attempted to generate it locally, but the process is too slow.

**Comment by maovshao** [comment] 2024-05-06 06:32
In fact, Pfam has provided Pfam domain results of all proteins in uniprot for everyone to download (https://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.regions.uniprot.tsv.gz). Maybe it's because Pfam's file download system has poor guidance, and I also looked for it for a long time.

Anyway, I hope this reply is helpful to you.

Best.

**Comment by changweioy** [comment] 2024-05-29 10:45
Hi, I conducted a test using a protein sequence from an influenza virus, with the target database set as Swiss-Prot. I observed substantial discrepancies between the results obtained from the official web server and my local setup. Below are the top ten hits ranked by similarity, first as per the official website and then my local results.
![gov](https://github.com/maovshao/PLMSearch/assets/9460156/1a74a784-ecb2-4802-aa6a-d1d03ba9e6cc)
![local](https://github.com/maovshao/PLMSearch/assets/9460156/874d0623-01af-4305-8b0f-211961abd9a0)

Is the version on GitHub inconsistent with the one deployed on the official website? Alternatively, could you supply the temporary files generated during the official website's operation: embdding.pkl and pfam for query sequence?

**Comment by maovshao** [comment] 2024-05-30 05:37
Thanks for your feedback.

I carefully checked the result you got from the server. The reason for the difference in results is that the Swiss-Prot dataset used in our paper (the same as in the GitHub repository) and the Swiss-Prot dataset used on the server are of different sizes. You can refer to **Supplementary Table 16 Datasets** in our supplementary material. For your convenience, I show this table below.

<img width="523" alt="image" src="https://github.com/maovshao/PLMSearch/assets/42936928/60874c48-8950-4a67-8c59-fe42e31cd3f7">

As you can see, **Swiss-Prot** in **Test** contains only **430,140** proteins, while **Swiss-Prot (unfiltered)** in **Target datasets on web server** contains **568,744** proteins. This is explained in detail in our paper. In short, in order to avoid potential data leakage during testing, we filtered **Swiss-Prot** during testing to avoid proteins with high sequence identity with the training data.

Our GitHub repository is mainly to facilitate other researchers to reproduce our work, so it contains the Swiss-Prot used in our tests to ensure consistent experimental results. I checked and found that the protein you searched from the web server is not included in the filtered Swiss-Prot (**plmsearch_data/swissprot/protein.fasta**), so PLMSearch cannot find it. You can also confirm it yourself.

Finally, since the server handles a large number of requests every day, a large number of **embeddings and pfam results** will be generated. Due to the limited storage space of the server, these embeddings are often only generated in memory for search, and then cleaned up and not saved. If it is really needed by most users, we may update it in subsequent versions.

Hope this reply is helpful to you.

Best.

**Comment by changweioy** [comment] 2024-05-30 06:12
Your response has clarified my doubts. Thank you!

**Closed as completed** 2024-05-30 06:54 UTC
Labels: help wanted

**Comment by maovshao** [comment] 2024-05-30 09:51
By the way, we have uploaded the Dataset of PLMSearch Web Server in [Zenodo](https://zenodo.org/records/11393990). Enjoy it.
